version: "3.7"
services:


  #############################################################################################
  ###                           Document Distribution Webservice                            ###
  #############################################################################################
  webservice:
    container_name: webservice
    hostname: webservice
    build:
      context: .
      dockerfile: Dockerfile.webservice
      args:
        - MVN_PROFILE=webservice
        - SKIP_TESTS=true
    ports:
      - "8080:8080"
    environment:
      - MAILAPI_URL=http://mailservice:8090/api/v1/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
  
  #############################################################################################
  ###                                  Mail Service API                                     ###
  #############################################################################################
  mailservice:
    container_name: mailservice
    hostname: mailservice
    build:
      context: .
      dockerfile: Dockerfile.mailservice
      args:
        - MVN_PROFILE=mailservice
        - SKIP_TESTS=true
    ports:
      - "8090:8090"
    environment:
      - EXCHANGE_SERVER=${EXCHANGE_SERVER}
      - EXCHANGE_ACCOUNT=${EXCHANGE_ACCOUNT}
      - EXCHANGE_ENDPOINT=${EXCHANGE_ENDPOINT}  
      - EXCHANGE_USERNAME=${EXCHANGE_USERNAME}
      - EXCHANGE_PASSWORD=${EXCHANGE_PASSWORD}
      - EXCHANGE_FOLDER_PATH=${EXCHANGE_FOLDER_PATH}
      - EXCHANGE_SAVE_IN_SENT=${EXCHANGE_SAVE_IN_SENT}
      - PDF_USERNAME=${PDF_USERNAME}
      - PDF_PASSWORD=${PDF_PASSWORD}
      - PDF_ENDPOINT=${PDF_ENDPOINT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin

  #############################################################################################
  ###                                  Fax Listener Service                                 ###
  #############################################################################################
  faxlistener:
    container_name: faxlistener
    hostname: faxlistener
    build:
      context: .
      dockerfile: Dockerfile.faxlistener
      args:
        - MVN_PROFILE=fax-listener
        - SKIP_TESTS=true
    ports:
      - "8083:8083"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
      
  #############################################################################################
  ###                                 REDIS SERVER                                          ###
  #############################################################################################
  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    restart: always

  #############################################################################################
  ###                                 REDIS COMMANDER                                       ###
  #############################################################################################
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=admin
    ports:
      - "8082:8081"

volumes:
  data-redis:
    driver: local
