version: "3.7"
services:

  #############################################################################################
  ###                           Document Distribution Webservice                            ###
  #############################################################################################
  webservice:
    container_name: webservice
    hostname: webservice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SKIP_TESTS=true
        - ENABLE_SPLUNK=${ENABLE_SPLUNK:-false}
    ports:
      - "8080:8080"
    environment:
      - EXCHANGE_ENDPOINT=${EXCHANGE_ENDPOINT}  
      - EXCHANGE_USERNAME=${EXCHANGE_USERNAME}
      - EXCHANGE_PASSWORD=${EXCHANGE_PASSWORD}
      - EXCHANGE_SAVE_IN_SENT=${EXCHANGE_SAVE_IN_SENT}
      - FAX_FORMAT=${FAX_FORMAT}
      - PDF_ENDPOINT=${PDF_ENDPOINT}
      - PDF_USERNAME=${PDF_USERNAME}
      - PDF_PASSWORD=${PDF_PASSWORD}
      - CALLBACK_ENDPOINT=${CALLBACK_ENDPOINT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
      - LOGLEVEL_DISPATCHERSERVLET=DEBUG
      
  #############################################################################################
  ###                                 REDIS SERVER                                          ###
  #############################################################################################
  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    restart: always

  #############################################################################################
  ###                                 REDIS COMMANDER (UI for redis)                        ###
  #############################################################################################
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=admin
    ports:
      - "8081:8081"

volumes:
  data-redis:
    driver: local
