package ca.bc.gov.ag.efax.graph.utils;

public class EFaxGraphConstants {
	
	public final static String dateFormat = "yyyy-MM-dd";
	
	public static final String ExpiryWarningSubject = "MS Graph API Credentials for the eFax service to expire soon.";
	public static final String ExpiryWarningMsg = "Hello. \n\nThere are %d days remaining before the MS Graph API credentials (secret key) will expire for the application %s. \nPlease refresh these credentials as soon as possible and update the relevant OpenShift namespace with the new key.\n\nThis message is autogenerated and will halt once the key is updated." ;

}
