server:
  port: ${SERVER_PORT:8083}
    
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:admin}

exchange:
  service:  
    endpoint: ${EXCHANGE_ENDPOINT:}
    username: ${EXCHANGE_USERNAME:}
    password: ${EXCHANGE_PASSWORD:}
  poller:  
    enabled: true
    # Interval (in milliseconds) of how often to poll the exchange server email inbox  
    interval: 300000    # 5 minutes 
    
logging:
  level:
    root: ${LOGGER_ROOT:INFO}
    ca.bc.gov.ag: TRACE
