name: Build Efax Webservice Image and Push to Openshift 4 Registry

on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'
            
      - name: Login to Openshift Docker
        run : |
          docker login ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY }} -u ${{ secrets.OPENSHIFT4_SA_USERNAME }} -p ${{ secrets.OPENSHIFT4_SA_PASSWORD }}
          
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Get Java Project Version 
        run: |  
          _version=$(.github/helpers/latest_java_version.sh)
          echo "LATEST_VERSION=$_version" >> $GITHUB_ENV
            
      - name: Build the Docker image
        run: |            
          docker-compose build webservice

      - name: Check Version
        if: env.LATEST_VERSION == '0.0.1-SNAPSHOT'
        run: |  
          echo "Version IS 0.0.1-SNAPSHOT"
          
      - name: Docker Tag Version
        run: |  
          docker tag jag-efax_webservice ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE }}/jag-efax-webservice:${{ env.LATEST_VERSION }}
          
      - name: Docker Push Version
        run: |  
          docker push ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE }}/jag-efax-webservice:${{ env.LATEST_VERSION }}    
      
      - name: Deploy to DEV
        run: |  
          echo "-----------------------"
          echo "LATEST VERSION: ${{ env.LATEST_VERSION }}"
          echo "-----------------------"
          NAMESPACE=${{ secrets.OPENSHIFT_DEV_NAMESPACE }}
          APPLICATION_NAME=${{ secrets.APPLICATION_NAME }}
          LICENSE_PLATE=${{ secrets.LICENSE_PLATE }}
          DEV_ENVIRONMENT=${{ secrets.DEV_ENVIRONMENT }}
          ./.github/helpers/deploy_efax.sh $NAMESPACE $APPLICATION_NAME $LICENSE_PLATE $DEV_ENVIRONMENT ${{ env.LATEST_VERSION }}

