name: Builds the distribution proxy JAR

on:
  workflow_dispatch:
    branches: [main]

jobs:
  app-version:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-maven-app-version.yml@main
    with:
      working_directory: "./distribution-client-proxy"

  build:
    runs-on: ubuntu-latest
    needs:
      - app-version

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode clean package -Pdistribution-client-proxy -DskipTests

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: "distribution-client-proxy-${{ needs.app-version.outputs.app-version }}.jar"
          path: |
            /home/runner/work/jag-efax/jag-efax/distribution-client-proxy/target/distribution-client-proxy-${{ needs.app-version.outputs.app-version }}-jar-with-dependencies.jar
          retention-days: 14


