name: Builds the distribution proxy JAR

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode clean package -Pdistribution-client-proxy -DskipTests



