name: TEST Deploy Efax Webservice 

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.EFAX_ARTIFACTORY_USERNAME }}
          password: ${{ secrets.EFAX_ARTIFACTORY_PASSWORD }}

      - name: Docker Pull Dev Version
        run: |  
          docker pull artifacts.developer.gov.bc.ca/edde-jag-efax-web/jag-efax-webservice:dev 
      
      - name: Docker Push Tag and Push Test Version
        run: | 
          docker tag artifacts.developer.gov.bc.ca/edde-jag-efax-web/jag-efax-webservice:dev artifacts.developer.gov.bc.ca/edde-jag-efax-web/jag-efax-webservice:test
          docker push artifacts.developer.gov.bc.ca/edde-jag-efax-web/jag-efax-webservice:test   
      